language: rust

rust:
  - stable
  - beta
  - nightly

script:
    - cargo build --verbose
    if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test --verbose; fi;
    - cargo doc --verbose

after_success:
    - curl http://docs.piston.rs/travis-doc-upload.sh | sh
