[package]
name = "imageproc"
version = "0.9.0"
authors = ["theotherphil"]
license = "MIT"
description = "Image processing operations"
readme = "README.md"
homepage = "https://github.com/PistonDevelopers/imageproc"
exclude = ["examples/*.ttf"]

[dependencies]
conv = "0.3.1"
image = "0.14.0"
itertools = "0.6.0"
nalgebra = "0.11"
num = "0.1.27"
quickcheck = "0.2.24"
rand = "0.3.11"
rusttype = "0.2.1"
rayon = "0.7.0"

[profile.release]
opt-level = 3
debug = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
