[package]
name = "imageproc"
version = "0.1.0"
authors = ["theotherphil"]
license = "MIT"
description = "Image processing operations"
readme = "README.md"
homepage = "https://github.com/PistonDevelopers/imageproc"

[dependencies]
conv = "0.3.1"
image = "0.3.14"
itertools = "0.4.2"
nalgebra = "0.3.0"
num = "0.1.27"
rand = "0.3.11"

[profile.release]
opt-level = 3
debug = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
